---
title: "Simple document"
output: github_document
---

```{r}
library(tidyverse)
```

Let's import the 'FAS_litters.csv' csv using a relative path.

```{r}
litters_df = 
  read.csv("data/FAS_litters.csv")

litters_df =
  janitor::clean_names(litters_df)

pups_df = 
  read.csv("data/FAS_pups.csv")

pups_df =
  janitor::clean_names(pups_df)
```

## 'select'

```{r}
select(litters_df, group, litter_number, gd0_weight, pups_born_alive)

select(litters_df, group:gd_of_birth)

select(litters_df, -pups_survive)
```

```{r}
filter(litters_df, group == "Con7")

filter(litters_df, group == "Mod8")

filter(litters_df, group != "Con7")

filter(litters_df, gd0_weight > 20)

filter(litters_df, group == "Con7" | group == "Con8")

filter(litters_df, group %in% c("Con7", "Con8"))

filter(litters_df, !(group == "Con7"))

filter(litters_df, group %in% c("Con7", "Con8"), gd0_weight > 20)
```

what about missing rows
```{r}
drop_na(litters_df)
drop_na(litters_df, gd0_weight)
```

## 'mutate'

this is used to add or change variables.

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)

mutate(litters_df,  group = str_to_lower(group))

mutate(
  litters_df,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```

## 'arrange'

```{r}
arrange(litters_df, gd0_weight)
```

## pipes

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv") |>
  janitor::clean_names() |>
  select(-starts_with("pups")) |>
  mutate(
    group = str_to_lower(group),
    wt_gain = gd18_weight - gd0_weight
  ) |>
  drop_na(wt_gain) |>
  arrange(group, wt_gain)
```

```{r}

```